codecov:
  require_ci_to_pass: true

coverage:
  status:
    project:
      default:
        enabled: no
    patch:
      default:
        enabled: no
    changes:
      default:
        enabled: no

github_checks:
  annotations: false
