paths:
  sandbox_path: $_/../../sandbox
  tier_daq: $_/../daq/generated/tier/daq
  tier_raw_blind: ""

  workflow: $_/workflow

  metadata: $_/inputs
  config: $_/inputs/dataprod/config
  par_overwrite: $_/inputs/dataprod/overrides
  chan_map: $_/inputs/hardware/configuration
  detector_status: $_/inputs/datasets
  detector_db: $_/inputs/hardware/detectors

  tier: $_/generated/tier
  tier_raw: /data2/public/prodenv/prod-blind/ref-raw/generated/tier/raw
  tier_tcm: $_/generated/tier/tcm
  tier_dsp: $_/generated/tier/dsp
  tier_hit: $_/generated/tier/hit
  tier_ann: $_/generated/tier/ann
  tier_evt: $_/generated/tier/evt
  tier_psp: $_/generated/tier/psp
  tier_pht: $_/generated/tier/pht
  tier_pan: $_/generated/tier/pan
  tier_pet: $_/generated/tier/pet
  tier_skm: $_/generated/tier/skm

  par: $_/generated/par
  par_raw: $_/generated/par/raw
  par_tcm: $_/generated/par/tcm
  par_dsp: $_/generated/par/dsp
  par_hit: $_/generated/par/hit
  par_evt: $_/generated/par/evt
  par_psp: $_/generated/par/psp
  par_pht: $_/generated/par/pht
  par_pet: $_/generated/par/pet

  plt: $_/generated/plt
  log: $_/generated/log

  tmp_plt: $_/generated/tmp/plt
  tmp_log: $_/generated/tmp/log
  tmp_filelists: $_/generated/tmp/filelists
  tmp_par: $_/generated/tmp/par

  src: $_/software/python/src
  install: $_/.snakemake/legend-dataflow/venv

table_format:
  raw: ch{ch:07d}/raw
  dsp: ch{ch:07d}/dsp
  psp: ch{ch:07d}/dsp
  hit: ch{ch:07d}/hit
  pht: ch{ch:07d}/hit
  evt: "{grp}/evt"
  pet: "{grp}/evt"
  skm: "{grp}/skm"
  tcm: hardware_tcm_1

execenv:
  local:
    env:
      HDF5_USE_FILE_LOCKING: "False"
      LGDO_BOUNDSCHECK: "false"
      DSPEED_BOUNDSCHECK: "false"
      PYGAMA_PARALLEL: "false"
      PYGAMA_FASTMATH: "false"
      DISABLE_TQDM: "True"
  lngs:
    cmd: apptainer exec
    arg: $PRODENV/containers/legendexp_legend-base_latest_20241110203225.sif
    env:
      HDF5_USE_FILE_LOCKING: "False"
      LGDO_BOUNDSCHECK: "false"
      LGDO_CACHE: "false"
      DSPEED_BOUNDSCHECK: "false"
      PYGAMA_PARALLEL: "false"
      PYGAMA_FASTMATH: "false"
      DISABLE_TQDM: "True"
  nersc:
    cmd: shifter
    arg: " --image legendexp/legend-base:latest"
    env:
      HDF5_USE_FILE_LOCKING: "FALSE"
      LGDO_BOUNDSCHECK: "false"
      DSPEED_BOUNDSCHECK: "false"
      PYGAMA_PARALLEL: "false"
      PYGAMA_FASTMATH: "false"

legend_metadata_version: refactor
